# Generated by Django 5.2.12 on 2026-03-15 10:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Hommes', 'Hommes'), ('Femmes', 'Femmes')], max_length=20, unique=True, verbose_name='Catégorie')),
                ('image', cloudinary.models.CloudinaryField(help_text='Image par défaut pour tous les produits de cette catégorie', max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image de Catégorie',
                'verbose_name_plural': 'Images de Catégories',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Image spécifique à ce produit (laissez vide pour utiliser l'image par défaut de la catégorie)", max_length=255, null=True, verbose_name='image'),
        ),
    ]
