# Generated by Django 5.2.9 on 2025-12-10 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
                ('prix', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('devise', models.CharField(choices=[('FCFA', 'FCFA'), ('MAD', 'MAD'), ('EUR', 'EUR'), ('USD', 'USD')], default='FCFA', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['country', 'city', 'name'],
            },
        ),
    ]
