# Generated by Django 5.2.9 on 2025-12-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='devise',
            field=models.CharField(blank=True, choices=[('FCFA', 'FCFA'), ('MAD', 'MAD'), ('EUR', 'EUR'), ('USD', 'USD'), ('MRU', 'MRU'), ('GNF', 'GNF'), ('GHS', 'GHS'), ('XAF', 'XAF'), ('CDF', 'CDF')], help_text='Devise optionnelle selon le pays', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='whatsapp',
            field=models.CharField(max_length=50),
        ),
    ]
