# Generated by Django 5.2.9 on 2025-12-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_devise_alter_supplier_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='localisation',
            field=models.CharField(blank=True, help_text='Ex: quartier, rue ou détails supplémentaires de la ville', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='whatsapp',
            field=models.CharField(help_text='Numéros multiples possibles séparés par /', max_length=200),
        ),
    ]
