# Generated by Django 5.2.9 on 2025-12-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_localisation_alter_supplier_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, help_text='Nom du fournisseur (optionnel)', max_length=100, null=True),
        ),
    ]
